// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 314a6f8642
// Version Date: Wed 26 Aug 2020 07:22:55 PM UTC

package main

import (
	"flag"

	// This Service
	"github.com/adamryman/truss_example/svc/server"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	server.Run(server.DefaultConfig)
}
